### PR TITLE
Fix repo links and add ci targets

### PR DESCRIPTION
**Pull request by elpiel**

### CODE REVIEW

**Review by robin-nitrokey — APPROVED** [review]
Looks good, thank you!

**Comment by elpiel** [comment]
You're welcome. Let's see if windows ci build actually is able to build successfully though :sweat_smile: given #37

**Comment by sullivanmj** [comment]
I tried to run the tests on Windows 11 via `cargo test` with my changes in #40, and got a new build error. It looked like some linker/multiple definition issue. If you'd like, I can create a new issue with the error output when I'm back at my machine.

**Comment by elpiel** [comment]
The changes in this PR don't actually change anything in the code, only docs & CI. It would be better to track down the issue and fix it in #40 or a subsequent PR I suppose.

**Comment by elpiel** [comment]
@sullivanmj you can also see the latest comment of @robin-nitrokey regarding the build error you had: https://github.com/trussed-dev/littlefs2/issues/37#issuecomment-1516944738

**Comment by sullivanmj** [comment]
@elpiel understood - thanks for the info, I'm still very green with Rust & Cargo. As my original PR fixed and unblocked me, I'll file a new issue.

**Pull request merged**
